LibraryManagementSystem/LibraryManagementSystem/Areas/Admin/Controllers/AuthorController.cs
using LibraryManagementSystem.Areas.Admin.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LibraryManagementSystem.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AuthorController : Controller
    {
        private readonly ILogger<AuthorController> _logger;

        public AuthorController(ILogger<AuthorController> logger)
        {
            _logger = logger;
        }
        public IActionResult CreateAuthor()
        {
            var model = new CreateAuthorModel();
            return View(model);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult CreateAuthor(CreateAuthorModel model)
        {
            if (ModelState.IsValid)
            {
                bool IsAuthorCreated = false;
                try
                {
                    model.CreateAuthor();
                    IsAuthorCreated = true;
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "Failed to create Author");
                    _logger.LogError(ex, "Create Author Failed");
                }

                if (IsAuthorCreated)
                    return RedirectToAction(nameof(CreateAuthor));
            }
            return View(model);
        }
    }
}

LibraryManagementSystem/LibraryManagementSystem/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LibraryManagementSystem.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

LibraryManagementSystem/LibraryManagementSystem/Areas/Admin/Views/Author/CreateAuthor.cshtml
@model CreateAuthorModel
@{
    ViewData["Title"] = "Create";
}
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Create A New Author</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Create Author</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-info">
                    <div class="card-header">
                        <h3 class="card-title">Create A New Author</h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <form class="form-horizontal" method="post" asp-controller="Author"
                          asp-action="CreateAuthor" asp-antiforgery="true">
                        <div asp-validation-summary="All" class="text-danger"></div>
                        <div class="card-body">
                            <div class="form-group row">
                                <label asp-for="Name" class="col-sm-2 col-form-label">Name</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control" asp-for="Name"
                                           id="name" placeholder="Product Name">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label asp-for="DateOfBirth" class="col-sm-2 col-form-label">DateOfBirth</label>
                                <div class="col-sm-10">
                                    <input type="datetime" asp-for="DateOfBirth" class="form-control"
                                           id="DateOfBirth" placeholder="DateOfBirth">
                                </div>
                            </div>
                        </div>
                        <!-- /.card-body -->
                        <div class="card-footer">
                            <button type="submit" class="btn btn-info">Create</button>
                            <a asp-action="Index" asp-controller="Dashboard"
                               class="btn btn-default float-right">Cancel</a>
                        </div>
                        <!-- /.card-footer -->
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>