SocialNetwork/SocialNetwork/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SocialNetwork.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

SocialNetwork/SocialNetwork/Areas/Admin/Controllers/PhotoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SocialNetwork.Areas.Admin.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.IO;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
using SocialNetwork.Models;

namespace SocialNetwork.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class PhotoController : Controller
    {
        private readonly ILogger<PhotoController> _logger;

        public PhotoController(ILogger<PhotoController> logger)
        {
            _logger = logger;
        }
        public IActionResult CreatePhoto()
        {
            var model = new CreatePhotoModel();
            return View(model);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult CreatePhoto(CreatePhotoModel model)
        {
            if (ModelState.IsValid)
            {
                bool IsCreatePhoto = false;
                try
                {
                    model.CreatePhoto();
                    IsCreatePhoto = true;
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "Failed to create Photo");
                    _logger.LogError(ex, "Create Photo Failed");
                }
                if (IsCreatePhoto)
                    return RedirectToAction(nameof(CreatePhoto));
            }

            return View(model);
        }

        public IActionResult GetPhotoDataView()
        {
            var model = new GetPhotoModel();
            return View(model);
        }

        public JsonResult GetPhotoData()
        {
            var dataTablesModel = new DataTablesAjaxRequestModel(Request);
            var model = new GetPhotoModel();
            var data = model.GetAllPhotos(dataTablesModel);
            return Json(data);
        }

        public IActionResult AllPhotosWithEditAndDeleteButton()
        {
            var model = new GetPhotoModel();
            return View(model);
        }

        public IActionResult EditPhoto(int id)
        {
            var model = new EditPhotoModel();
            model.LoadPhotoDataForEdit(id);
            return View(model);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult EditPhoto(EditPhotoModel model)
        {
            if (ModelState.IsValid)
            {
                model.Update();
                return RedirectToAction(nameof(AllPhotosWithEditAndDeleteButton));
            }

            return View(model);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult DeletePhoto(int id)
        {
            var model = new DeletePhotoModel();

            model.DeletePhoto(id);

            return RedirectToAction(nameof(AllPhotosWithEditAndDeleteButton));
        }
    }
}

SocialNetwork/SocialNetwork/Areas/Admin/Views/Photo/AllPhotosWithEditAndDeleteButton.cshtml
@model GetPhotoModel
@{
    ViewData["Title"] = "Edit/Delete Photo";
}

@section Styles
{
    <link rel="stylesheet" href="/admin/plugins/datatables-bs4/css/dataTables.bootstrap4.css">
}

@section Scripts
{
    <script src="/admin/plugins/datatables/jquery.dataTables.js"></script>
    <script src="/admin/plugins/datatables-bs4/js/dataTables.bootstrap4.js"></script>
    <script>
        $(function () {
            $('#Photos').DataTable({
                "processing": true,
                "serverSide": true,
                "ajax": "/Admin/Photo/GetPhotoData",

                "columnDefs": [
                    {
                        "orderable": false,
                        "targets": 1,
                        "render": function (data, type, row) {
                            return `<img src=${data} width='70px' height='70px'/>`;
                        }
                    },

                    {
                        "orderable": false,
                        "targets": 2,
                        "render": function (data, type, row) {
                            return `<button type="submit" class="btn btn-info btn-sm" onclick="window.location.href=
                                     '/admin/photo/EditPhoto/${data}'" value='${data}'>

                                        <i class="fas fa-pencil-alt">
                                        </i>
                                        Edit
                                    </button>
                                    <button type="submit" class="btn btn-danger btn-sm show-bs-modal" href="#"
                                                  data-id='${data}' value='${data}'>
                                        <i class="fas fa-trash">
                                        </i>
                                        Delete
                                    </button>`;
                        }
                    }
                ]
            });

            $('#Photos').on('click', '.show-bs-modal', function (event) {
                var id = $(this).data("id");
                var modal = $("#modal-default");
                modal.find('.modal-body p').text('Are you sure you want to delete this record?')
                $("#deleteId").val(id);
                $("#deleteForm").attr("action", "/admin/photo/deletephoto")
                modal.modal('show');
            });

            $("#deleteButton").click(function () {
                $("#deleteForm").submit();
            });

        });
    </script>
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Available Photos</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Photo</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">All Available Photos</h3>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <table id="Photos" class="table table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>Member Id</th>
                                <th>Image</th>
                                <th style="width:150px">Action</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>Member Id</th>
                                <th>Image</th>
                                <th>Action</th>
                            </tr>
                        </tfoot>
                    </table>
                    <partial name="_DeletePopupPartial">
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>
<!-- /.content -->

SocialNetwork/SocialNetwork/Areas/Admin/Views/Photo/CreatePhoto.cshtml
@model CreatePhotoModel
@{
    ViewData["Title"] = "Create";
}
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Create A New Photo</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Create Photo</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-info">
                    <div class="card-header">
                        <h3 class="card-title">Create A New Photo</h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <form class="form-horizontal" method="post" asp-controller="Photo"
                          asp-action="CreatePhoto" asp-antiforgery="true" enctype="multipart/form-data">
                        <div asp-validation-summary="All" class="text-danger"></div>
                        <div class="card-body">
                            <div class="form-group row">
                                <label asp-for="MemberId" class="col-sm-2 col-form-label">Member Id</label>
                                <div class="col-sm-10">
                                    <input type="number" class="form-control" asp-for="MemberId"
                                           id="MemberId" placeholder="Member Id">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label asp-for="PhotoFile" class="col-sm-2 col-form-label">upload Image</label>
                                <div class="col-sm-10">
                                    <input type="file" asp-for="PhotoFile"
                                           id="PhotoFile" placeholder="upload Image">
                                </div>
                            </div>
                        </div>
                        <!-- /.card-body -->
                        <div class="card-footer">
                            <button type="submit" class="btn btn-info">Create</button>
                            <a asp-action="Index" asp-controller="Dashboard"
                               class="btn btn-default float-right">Cancel</a>
                        </div>
                        <!-- /.card-footer -->
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

SocialNetwork/SocialNetwork/Areas/Admin/Views/Photo/EditPhoto.cshtml
@model EditPhotoModel
@{
    ViewData["Title"] = "Edit Photo";
}
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Edit Photo</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Edit Photo</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-info">
                    <div class="card-header">
                        <h3 class="card-title">Edit Photo</h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <form class="form-horizontal" method="post" asp-controller="Photo"
                          asp-action="EditPhoto" asp-antiforgery="true" enctype="multipart/form-data">
                        <div asp-validation-summary="All" class="text-danger"></div>

                        <input type="hidden" asp-for="Id" />
                        <div class="card-body">
                            <div class="form-group row">
                                <label asp-for="MemberId" class="col-sm-2 col-form-label">Mmber Id</label>
                                <div class="col-sm-10">
                                    <input type="number" class="form-control" asp-for="MemberId"
                                           id="MemberId" placeholder="Member Id">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label asp-for="PhotoFile" class="col-sm-2 col-form-label">Image</label>
                                <img src=@Model.PhotoFileName asp-append-version="true" height="70" width="70" class="img-thumbnail"/>
                                <div class="col-sm-10">
                                    <input type="file" asp-for="PhotoFile" id="PhotoFile" placeholder="image">
                                </div>
                            </div>
                        </div>
                        <!-- /.card-body -->
                        <div class="card-footer">
                            <button type="submit" class="btn btn-info">Edit</button>
                            <a asp-action="AllPhotosWithEditAndDeleteButton" asp-controller="Photo"
                               class="btn btn-default float-right">Cancel</a>
                        </div>
                        <!-- /.card-footer -->
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

SocialNetwork/SocialNetwork/Areas/Admin/Views/Photo/GetPhotoDataView.cshtml
@model GetPhotoModel
@{
    ViewData["Title"] = "GetPhotoDataView";
}

@section Styles
{
    <link rel="stylesheet" href="/admin/plugins/datatables-bs4/css/dataTables.bootstrap4.css">
}

@section Scripts
{
    <script src="/admin/plugins/datatables/jquery.dataTables.js"></script>
    <script src="/admin/plugins/datatables-bs4/js/dataTables.bootstrap4.js"></script>
    <script>
        $(function () {
            $('#Photos').DataTable({
                "processing": true,
                "serverSide": true,
                "ajax": "/Admin/Photo/GetPhotoData",

                "columnDefs": [
                    {
                        "orderable": false,
                        "targets": 1,
                        "render": function (data, type, row) {
                            return `<img src=${data} width='70px' height='70px'/>`;
                        }
                    }
                ]
            });
        });
    </script>
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Available Photos</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Photos</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">All Available Photos</h3>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <table id="Photos" class="table table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>Member Id</th>
                                <th>Photo</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>Member Id</th>
                                <th>Photo</th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>
<!-- /.content -->