AttendanceSystem/AttendanceSystem/Areas/Admin/Controllers/AttendanceController.cs
using AttendanceSystem.Areas.Admin.Models;
using AttendanceSystem.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AttendanceSystem.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AttendanceController : Controller
    {
        private readonly ILogger<AttendanceController> _logger;

        public AttendanceController(ILogger<AttendanceController> logger)
        {
            _logger = logger;
        }
        public IActionResult CreateAttendance()
        {
            var model = new CreateAttendanceModel();
            return View(model);
        }
        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult CreateAttendance(CreateAttendanceModel model)
        {
            if (ModelState.IsValid)
            {
                bool IsCreateAttendence = false;
                try
                {
                    model.CreateAttendance();
                    IsCreateAttendence = true;
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "Failed to create Attendance");
                    _logger.LogError(ex, "Create Attendance Failed");
                }
                if (IsCreateAttendence)
                    return RedirectToAction(nameof(CreateAttendance));
            }

            return View(model);
        }

        public IActionResult GetAttendanceDataView()
        {
            var model = new GetAttendanceModel();
            return View(model);
        }

        public JsonResult GetAttendanceData()
        {
            var dataTablesModel = new DataTablesAjaxRequestModel(Request);
            var model = new GetAttendanceModel();
            var data = model.GetAllAttendance(dataTablesModel);
            return Json(data);
        }

        public IActionResult AllAttendanceWithEditAndDeleteButton()
        {
            var model = new GetAttendanceModel();
            return View(model);
        }

        public IActionResult EditAttendance(int id)
        {
            var model = new EditAttendanceModel();
            model.LoadAttendanceDataForEdit(id);
            return View(model);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult EditAttendance(EditAttendanceModel model)
        {
            if (ModelState.IsValid)
            {
                model.Update();
                return RedirectToAction(nameof(AllAttendanceWithEditAndDeleteButton));
            }

            return View(model);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult DeleteAttendance(int id)
        {
            var model = new DeleteAttendanceModel();

            model.DeleteAttendance(id);

            return RedirectToAction(nameof(AllAttendanceWithEditAndDeleteButton));
        }
    }
}

AttendanceSystem/AttendanceSystem/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AttendanceSystem.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

AttendanceSystem/AttendanceSystem/Areas/Admin/Controllers/StudentController.cs
using AttendanceSystem.Areas.Admin.Models;
using AttendanceSystem.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AttendanceSystem.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class StudentController : Controller
    {
        private readonly ILogger<StudentController> _logger;

        public StudentController(ILogger<StudentController> logger)
        {
            _logger = logger;
        }
        public IActionResult CreateStudent()
        {
            var model = new CreateStudentModel();
            return View(model);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult CreateStudent(CreateStudentModel model)
        {
            if (ModelState.IsValid)
            {
                bool IsCreateStudent = false;
                try
                {
                    model.CreateStudent();
                    IsCreateStudent = true;
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "Failed to create Student");
                    _logger.LogError(ex, "Create Student Failed");
                }
                if (IsCreateStudent)
                    return RedirectToAction(nameof(CreateStudent));
            }
            return View(model);
        }

        public IActionResult GetStudentDataView()
        {
            var model = new GetStudentModel();
            return View(model);
        }

        public JsonResult GetStudentData()
        {
            var dataTablesModel = new DataTablesAjaxRequestModel(Request);
            var model = new GetStudentModel();
            var data = model.GetAllStudents(dataTablesModel);
            return Json(data);
        }

        public IActionResult AllStudentsWithEditAndDeleteButton()
        {
            var model = new GetStudentModel();
            return View(model);
        }

        public IActionResult EditStudent(int id)
        {
            var model = new EditStudentModel();
            model.LoadStudentDataForEdit(id);
            return View(model);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult EditStudent(EditStudentModel model)
        {
            if (ModelState.IsValid)
            {
                model.Update();
                return RedirectToAction(nameof(AllStudentsWithEditAndDeleteButton));
            }

            return View(model);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult DeleteStudent(int id)
        {
            var model = new DeleteStudentModel();

            model.DeleteStudent(id);

            return RedirectToAction(nameof(AllStudentsWithEditAndDeleteButton));
        }

    }
}

AttendanceSystem/AttendanceSystem/Areas/Admin/Views/Shared/_AdminMenuPartial.cshtml
<nav class="mt-2">
    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <!-- Add icons to the links using the .nav-icon class
    with font-awesome or any other icon font library -->
        <li class="nav-item">
            <a asp-action="Index" asp-controller="Dashboard" class="nav-link">
                <i class="nav-icon fas fa-th"></i>
                <p>
                    Home
                </p>
            </a>
        </li>
        
        <li class="nav-item">
            <a asp-action="CreateStudent" asp-controller="Student" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>
                    Add Student
                </p>
            </a>
        </li>

        <li class="nav-item">
            <a asp-action="GetStudentDataView" asp-controller="Student" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>
                    Show Student
                </p>
            </a>
        </li>

        <li class="nav-item">
            <a asp-action="AllStudentsWithEditAndDeleteButton" asp-controller="Student" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>
                    Edit/Delete Student
                </p>
            </a>
        </li>

        <li class="nav-item">
            <a asp-action="CreateAttendance" asp-controller="Attendance" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>
                    Add Attendance
                </p>
            </a>
        </li>

        <li class="nav-item">
            <a asp-action="GetAttendanceDataView" asp-controller="Attendance" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>
                    Get Attendance Info
                </p>
            </a>
        </li>

        <li class="nav-item">
            <a asp-action="AllAttendanceWithEditAndDeleteButton" asp-controller="Attendance" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>
                    Edit/Delete Attendance
                </p>
            </a>
        </li>

    </ul>
</nav>